language: node_js

node_js:
  - 8

# branches:
#   only:
#     - master

jobs:
  include:
    - stage: unit tests
      node_js: lts/*
      skip_cleanup: true
      script:
        - yarn test:components

    - stage: regression tests
      node_js: lts/*
      skip_cleanup: true
      script:
        - yarn build:regression

    - stage: release
      if: branch = master
      node_js: lts/*
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
        - yarn semantic-release
